- CMake/FindMINDSPORE.cmake
- src/drivers/devices/ascend/flowunit/mindspore_inference/CMakeLists.txt
- src/drivers/devices/ascend/flowunit/mindspore_inference/mindspore_inference.cc
- src/drivers/devices/ascend/flowunit/mindspore_inference/mindspore_inference.h
- src/drivers/devices/ascend/flowunit/mindspore_inference/test_toml/modelbox.test.mindspore.inference.in
- src/drivers/virtual/python/virtualdriver_python.cc
- src/libmodelbox/base/drivers/driver.cc
- src/libmodelbox/engine/data_context.cc
- src/libmodelbox/include/modelbox/data_context.h
> adjust external data send and close, add python support exception visiable, be suitable for ms 1.3.0

- CMake/FindDSMI.cmake
- src/drivers/devices/cuda/flowunit/torch/torch_inference_flowunit.cc
> change some logs of torch flowunit & be suitable for c78 dsmi

- test/unit/libmodelbox/base/thread_pool_test.cc
- test/unit/libmodelbox/engine/virtual_node_test.cc
Signed-off-by: CarlosLeeGit <CarlosLeeX@outlook.com>
> prevent threadpool unit test check fail

- src/drivers/devices/ascend/flowunit/padding/padding_flowunit.cc
> flowunit: fix padding error

- src/drivers/devices/ascend/flowunit/padding/padding_flowunit.cc
> flowunit: fix min width stride

- examples/flowunit/c++/CMakeLists.txt
> flowunit: add link library for example

- src/libmodelbox/base/device/device_manager.cc
- src/libmodelbox/base/include/modelbox/base/collector.h
> DeviceManager: first check device desc, then create device

- src/libmodelbox/engine/data_context.cc
- src/libmodelbox/engine/graph.cc
- test/mock/minimodelbox/mockflow.cc
- test/mock/minimodelbox/mockflow.h
- test/unit/libmodelbox/engine/node_test.cc
> Exception: add flowunit error through collaspe

- src/libmodelbox/engine/graph.cc
> Log: modify build graph error log

- src/libmodelbox/engine/graph.cc
- src/libmodelbox/flow/flow.cc
> Log: revert graph build log and add flow build graph print log

- src/drivers/devices/ascend/flowunit/crop/crop_flowunit.cc
- src/drivers/devices/ascend/flowunit/padding/padding_flowunit.cc
- src/drivers/devices/ascend/flowunit/padding/padding_flowunit.h
> fix: padding cannot put ori image to center of dest image

- examples/CMakeLists.txt
- examples/project/test/CMakeLists.txt
> build example faild

- examples/CMakeLists.txt
> remove build example

- src/drivers/devices/ascend/flowunit/padding/padding_flowunit.cc
- src/drivers/devices/ascend/flowunit/padding/padding_flowunit.h
> fix: align height greater than out image height

- src/drivers/devices/cuda/flowunit/inference/inference_flowunit_test.cc
- src/libmodelbox/engine/node.cc
- test/unit/libmodelbox/engine/node_test.cc
- test/unit/libmodelbox/flow_test.cc
> FlowUnit: remove config is_exception_visible in graph toml

- src/drivers/devices/cuda/core/driver_desc.cc
> FlowUnit: add cuda set device flag

- src/drivers/devices/ascend/flowunit/mindspore_inference/mindspore_inference_flowunit_test.cc
> FlowUnit: mindspore suit for batch size adjust

- src/drivers/devices/cuda/flowunit/video_decoder/video_decoder_flowunit.cc
add H.265 test video and skip decoding error frames using skip_error_frame parameter.
> fix H.265 decode failed

- src/libmodelbox/engine/external_data_simple.cc
- src/libmodelbox/engine/solution.cc
- src/libmodelbox/engine/virtual_node.cc
- src/libmodelbox/flow/flow.cc
- src/libmodelbox/include/modelbox/external_data_simple.h
- src/libmodelbox/include/modelbox/flow.h
- src/libmodelbox/include/modelbox/solution.h
- src/libmodelbox/include/modelbox/virtual_node.h
- test/mock/minimodelbox/mockflow.cc
- test/mock/minimodelbox/mockflow.h
- test/unit/libmodelbox/solution_test.cc
Signed-off-by: sunny <you@example.com>
代码先上传， 测试用例编译失败，暂没上传， 以文档的方式放在wiki上： https://clouddevops.huawei.com/domains/27505/wiki/8/WIKI2022021100425
> add solution framework

- src/drivers/devices/cpu/flowunit/tensorflow/flowunit_desc.cc
- src/drivers/devices/cuda/flowunit/tensorflow/flowunit_desc.cc
- src/drivers/inference_engine/tensorflow/tensorflow_inference_common.cc
- src/drivers/inference_engine/tensorflow/tensorflow_inference_common.h
> Inference: tensorflow support input/output name index and remove graph cache

- src/libmodelbox/base/include/modelbox/base/popen.h
- src/libmodelbox/base/utils/popen.cc
- test/unit/libmodelbox/base/popen_test.cc
安全popen函数，避免命令注入，支持命令超时，支持获取标准错误输出，关闭句柄，c++接口
> popen: add safe popen function

- src/drivers/devices/cuda/flowunit/torch/torch_inference_flowunit.cc
- src/drivers/inference_engine/tensorflow/tensorflow_inference_common.cc
> Inference: fix ConvertType bug

- examples/bin/create
- examples/flowunit/c++/CMakeLists.txt
- examples/flowunit/c++/example.cc
- examples/flowunit/c++/example.h
- examples/flowunit/python/example.py
- examples/project/CMakeLists.txt
- examples/project/thirdparty/CMake/local-package.in
- examples/project/thirdparty/CMake/pre-download.in
- examples/project/thirdparty/CMakeLists.txt
create --project --name "name" --path project-path
create --flowunit --type [python|infer|c++|yolo] --project-path project-path --device [cuda|cpu|ascend] --desc "this is a flowunit"
--input name=p1, device=[cpu|cuda|ascend] --output name=p2,device=[cpu,cuda,ascend]
> modelbox-tool: refactor create command.

- src/drivers/common/flowunit/image_process/image_process.cc
- src/drivers/devices/ascend/flowunit/inference/atc_inference_flowunit_test.cc
- src/drivers/devices/cpu/flowunit/color_transpose/color_transpose_flowunit.cc
- src/drivers/devices/cpu/flowunit/cv_crop/cv_crop_flowunit.cc
- src/drivers/devices/cpu/flowunit/image_decoder/image_decoder.cc
- src/drivers/devices/cpu/flowunit/padding/padding_flowunit.cc
- src/drivers/devices/cpu/flowunit/resize/resize_flowunit.cc
- src/drivers/devices/cpu/flowunit/video_decoder/video_decoder_flowunit.cc
- src/drivers/devices/cuda/flowunit/nppi_crop/nppi_crop_flowunit.cc
- src/drivers/devices/cuda/flowunit/nppi_resize/resize_flowunit.cc
- src/drivers/devices/cuda/flowunit/nv_image_decoder/nv_image_decoder.cc
- src/drivers/devices/cuda/flowunit/padding/padding_flowunit.cc
- src/drivers/devices/cuda/flowunit/video_decoder/video_decoder_flowunit.cc
- src/libmodelbox/base/include/modelbox/base/popen.h
> FlowUnit: fix cal rgb width_stride

- examples/bin/template
- examples/flowunit/python/example.toml
- examples/misc/modelbox-template-cmd.json.in
- src/libmodelbox/base/utils/utils.cc
- src/modelbox/server/plugin/editor/editor_plugin.cc
- src/modelbox/server/plugin/editor/editor_plugin.h
GET http://127.0.0.1:1104/editor/project?path=/root/a/
###
GET http://127.0.0.1:1104/editor/project?path=/root/a/a
###
GET http://127.0.0.1:1104/editor/project?path=/root/modelb/
###
GET http://127.0.0.1:1104/editor/project/list?path=/
###
GET http://127.0.0.1:1104/editor/project/list?path=%2Fusr%2Flocal
###
PUT http://127.0.0.1:1104/editor/project/create
{
"name":"hello",
"path":"/root/e"
}
###
PUT http://127.0.0.1:1104/editor/flowunit/create
{
"name":"hellocpap",
"lang": "c++",
"project-path": "/root/a",
"input": [
{"name": "in1"},
{"name": "in2"}
],
"output": [
{"name": "in1"},
{"name": "in2"}
],
"path":"/root/a"
}
###
PUT http://127.0.0.1:1104/editor/password/encode
{
"password":"password",
"sysrelated":false
}
> Editor: support template command API

- examples/CMakeLists.txt
- examples/bin/template
- examples/project/hello_world/desc.toml
- examples/project/hello_world/setup.sh
- examples/project/mnist/desc.toml
- examples/project/mnist/setup.sh
- src/demo/CMakeLists.txt
- src/demo/mnist/graph/CMakeLists.txt
- src/demo/mnist/graph/test_mnist.py
- src/libmodelbox/base/utils/popen.cc
> template: make special demo as template

- src/libmodelbox/engine/graph/graph_checker.cc
- src/libmodelbox/include/modelbox/graph_checker.h
- test/unit/libmodelbox/engine/graph_checker_test.cc
> GraphChecker: add check input ports ready and use tmp_color to compare.

- src/libmodelbox/engine/graph/graph_checker.cc
- src/libmodelbox/include/modelbox/graph_checker.h
- test/unit/libmodelbox/engine/graph_checker_test.cc
> GraphChecker: fix single port match node is condition check

- src/drivers/devices/ascend/flowunit/video_decoder/ascend_video_decode.cc
- src/drivers/devices/cpu/flowunit/video_decoder/ffmpeg_video_decoder.cc
- src/libmodelbox/engine/buffer.cc
- src/libmodelbox/engine/buffer_list.cc
- src/libmodelbox/include/modelbox/buffer.h
fix: delayed copy flag status error,need clear status
> fix: delayed copy flag status error

- examples/project/resize/src/graph/resize.toml
> UI: remove label

- src/drivers/devices/cuda/flowunit/torch/torch_inference_flowunit.cc
> Torch: add load model mutex

- src/drivers/common/python/modelbox_api/modelbox_api.cc
- src/drivers/common/python/modelbox_api/modelbox_api.h
- src/libmodelbox/base/drivers/register_flowunit.cc
- src/libmodelbox/base/include/modelbox/base/error_info.h
- src/libmodelbox/base/include/modelbox/base/register_flowunit.h
- src/libmodelbox/engine/api/flow_graph_desc.cc
- src/libmodelbox/engine/api/flow_node_desc.cc
- src/libmodelbox/engine/dynamic_graph/data_handler.cc
- src/libmodelbox/engine/dynamic_graph/modelbox_engine.cc
- src/libmodelbox/engine/external_data_simple.cc
- src/libmodelbox/engine/flowunit_manager.cc
- src/libmodelbox/engine/graph.cc
- src/libmodelbox/flow/flow.cc
- src/libmodelbox/include/modelbox/data_handler.h
- src/libmodelbox/include/modelbox/external_data_simple.h
- src/libmodelbox/include/modelbox/flow.h
- src/libmodelbox/include/modelbox/flow_graph_desc.h
- src/libmodelbox/include/modelbox/flow_node_desc.h
- src/libmodelbox/include/modelbox/flowunit.h
- src/libmodelbox/include/modelbox/graph.h
- src/libmodelbox/include/modelbox/modelbox_engine.h
- src/python/lib/modelbox.cc
- src/python/test/test_api_mode.py
- src/python/test/test_dynamic_graph.py
- test/function/CMakeLists.txt
- test/function/api_test.cc
- test/function/dynamic_graph_test.cc
Signed-off-by: bingo12345 <yangguangxu0927@126.com>
> add api mode

- src/drivers/common/flowunit/safe_http/http_util.cc
- src/drivers/common/flowunit/safe_http/http_util.h
- src/drivers/devices/cpu/flowunit/httpserver_async/httpserver_async.cc
- src/drivers/devices/cpu/flowunit/httpserver_async/httpserver_async.h
- src/drivers/devices/cpu/flowunit/httpserver_sync/httpserver_sync_test.cc
- src/drivers/devices/cpu/flowunit/httpserver_sync/receive/httpserver_sync_receive.cc
- src/drivers/devices/cpu/flowunit/httpserver_sync/receive/httpserver_sync_receive.h
> FlowUnit: Add http sync & async health check and set keep alive time

- src/drivers/devices/cpu/flowunit/httpserver_async/httpserver_async.cc
- src/drivers/devices/cpu/flowunit/httpserver_sync/httpserver_sync_test.cc
- src/drivers/devices/cpu/flowunit/httpserver_sync/receive/httpserver_sync_receive.cc
> FlowUnit: add http flowunit desc option

- src/libmodelbox/engine/graph/graph_checker.cc
- src/libmodelbox/include/modelbox/graph_checker.h
- test/unit/libmodelbox/engine/graph_checker_test.cc
fix bug: fix overhierarchy check node which is end_if node and expand/if-else/collapse node
> fix bug: fix overhierarchy check node

- src/drivers/common/flowunit/image_process/image_process.cc
- src/drivers/common/flowunit/image_process/image_process.h
- src/drivers/devices/ascend/flowunit/crop/crop_flowunit.cc
- src/drivers/devices/ascend/flowunit/crop/crop_flowunit.h
- src/drivers/devices/cpu/flowunit/cv_crop/CMakeLists.txt
- src/drivers/devices/cpu/flowunit/cv_crop/cv_crop_flowunit.cc
- src/drivers/devices/cpu/flowunit/cv_crop/cv_crop_flowunit.h
- src/drivers/devices/cpu/flowunit/cv_crop/cv_crop_flowunit_test.cc
- src/drivers/devices/cpu/flowunit/data_source_parser/data_source_parser_flowunit.h
- src/drivers/devices/cpu/flowunit/httpserver_sync/receive/httpserver_sync_receive.cc
- src/drivers/devices/cuda/flowunit/nppi_crop/CMakeLists.txt
- src/drivers/devices/cuda/flowunit/nppi_crop/nppi_crop_flowunit.cc
- src/drivers/devices/cuda/flowunit/nppi_crop/nppi_crop_flowunit.h
- src/drivers/devices/cuda/flowunit/padding/padding_flowunit.cc
> check crop roi is valid

- src/libmodelbox/base/include/modelbox/base/driver_api_helper.h
- src/libmodelbox/engine/buffer.cc
- src/libmodelbox/include/modelbox/buffer.h
> change buffer set error api

- src/drivers/common/python/modelbox_api/modelbox_api.cc
- src/drivers/common/python/modelbox_api/modelbox_api.h
- src/python/lib/modelbox.cc
- src/python/test/test_solution.py
1. Add the pybind binding of solution
2. Add the solution ut test
> Add solution's pybind binding and UT test

- src/libmodelbox/engine/graph/graph_checker.cc
- src/libmodelbox/include/modelbox/graph_checker.h
- test/unit/libmodelbox/engine/graph_checker_test.cc
node has the same name in input ports and output ports
> Bug: fix overhierarchy check 

- src/drivers/devices/cpu/flowunit/python/python_flowunit.cc
> bug: add reload mutex

- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/CMakeLists.txt
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_common/vcn_info.cc
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_common/vcn_info.h
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_restful_source_parser/CMakeLists.txt
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_restful_source_parser/driver_desc.cc
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_restful_source_parser/vcn_restful_client.cc
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_restful_source_parser/vcn_restful_client.h
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_restful_source_parser/vcn_restful_source_parser.cc
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_restful_source_parser/vcn_restful_source_parser.h
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_restful_source_parser/vcn_restful_source_parser_test.cc
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_restful_source_parser/vcn_restful_wrapper.cc
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_restful_source_parser/vcn_restful_wrapper.h
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_restful_source_parser/vcn_restful_wrapper_mock_test.cc
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_restful_source_parser/vcn_restful_wrapper_mock_test.h
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_source_parser/vcn_client.cc
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_source_parser/vcn_client.h
vcn is compatible with restful requests
> vcn is compatible with restful requests

- src/libmodelbox/base/include/modelbox/base/log.h
- src/libmodelbox/base/log/log.cc
- test/unit/libmodelbox/base/log_test.cc
增加设置logid接口
auto logid = modelbox::LogSetLogID("LOGID");
> Log: support setting log id

- src/libmodelbox/base/include/modelbox/base/utils.h
- src/libmodelbox/base/utils/utils.cc
- src/modelbox/server/plugin/tasks/modelbox_plugin.cc
modelbox plugin graph path support dir
> modelbox plugin graph path support dir

- src/modelbox/serving/main.cc
> bug: fix popen args and modify logs

- src/drivers/devices/cpu/flowunit/common_yolobox/yolobox_flowunit.h
> boundingbox no need virtual

- src/drivers/devices/cpu/flowunit/mindspore_lite_inference/test_toml/modelbox.test.mindspore.cpu.inference.encrypt.in
- src/drivers/devices/cuda/flowunit/mindspore_inference/test_toml/modelbox.test.mindspore.cuda.inference.encrypt.in
fix cpu and cuda mindspore model device unrelated
> mindspore model device unrelated

- examples/flowunit/plugin/output_broker/example.cc
- examples/flowunit/plugin/output_broker/example.h
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/obs_source_parser/obs_source_parser.h
- src/drivers/devices/cpu/flowunit/output_broker/broker_plugin/dis_output_broker/dis_output_broker.cc
- src/drivers/devices/cpu/flowunit/output_broker/broker_plugin/dis_output_broker/dis_output_broker.h
- src/drivers/devices/cpu/flowunit/output_broker/broker_plugin/obs_output_broker/obs_output_broker.cc
- src/drivers/devices/cpu/flowunit/output_broker/broker_plugin/obs_output_broker/obs_output_broker.h
- src/drivers/devices/cpu/flowunit/output_broker/broker_plugin/webhook_output_broker/webhook_output_broker.cc
- src/drivers/devices/cpu/flowunit/output_broker/broker_plugin/webhook_output_broker/webhook_output_broker.h
- src/drivers/devices/cpu/flowunit/output_broker/output_broker_flowunit.cc
- src/drivers/devices/cpu/flowunit/output_broker/output_broker_flowunit.h
- src/libmodelbox/include/modelbox/output_broker_plugin.h
Open() add param “SessionContext“
> output_broker plugin open() add session config

- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/obs_source_parser/obs_source_parser.cc
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/url_source_parser/url_source_parser.cc
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_restful_source_parser/vcn_restful_source_parser.cc
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vcn_source_parser/vcn_source_parser.cc
- src/drivers/devices/cpu/flowunit/data_source_parser/parser_plugin/vis_source_parser/vis_source_parser.cc
> obs retry param config error

- docker/Dockerfile.ascend.develop.ubuntu
- docker/Dockerfile.ascend.runtime.ubuntu
- docker/Dockerfile.cuda.develop.openeuler
- docker/Dockerfile.cuda.develop.ubuntu
- docker/Dockerfile.cuda.runtime.openeuler
- docker/Dockerfile.cuda.runtime.ubuntu
1. 修复cuda+tf镜像未安装tensorflow问题
2. 修复安装tensorrt依赖版本不一致问题
3. 修复安装systemd依赖包安装报错问题
> build: fix some issue

- .github/workflows/manual-build-with-image.yml
- .github/workflows/merge-request-ascend.yml
- .github/workflows/merge-request-cuda.yml
- .github/workflows/publish-modelbox-images.yml
- .github/workflows/unit-test-daily-on-device.yml
- .github/workflows/unit-test-pull-requests-on-device.yml
- docker/Dockerfile.ascend.develop.ubuntu
- docker/Dockerfile.ascend.runtime.ubuntu
- docker/artifact_check.sh
1. 门禁测试增加armd环境
2. 门禁测试环境在测试前安装代码编译的产物
3. ubuntu armd镜像构建时删除bionic-proposed源
> action: unittest add armd & fix armd image issue

- src/libmodelbox/base/config/configuration.cc
- src/libmodelbox/base/include/modelbox/base/configuration.h
- src/libmodelbox/base/include/modelbox/base/utils.h
- src/libmodelbox/base/utils/utils.cc
- src/modelbox/common/config.cc
- test/unit/libmodelbox/base/utils_test.cc
configuration support parse environment variable
> configuration support parse environment variable

- examples/flowunit/infer/example.toml
- src/drivers/devices/ascend/flowunit/inference/test_toml/modelbox.test.ascend.inference.in
- src/drivers/devices/ascend/flowunit/mindspore_inference/standard/test_toml/modelbox.test.mindspore.ascend.inference.encrypt.in
- src/drivers/devices/cpu/flowunit/mindspore_lite_inference/test_toml/modelbox.test.mindspore.cpu.inference.encrypt.in
- src/drivers/devices/cpu/flowunit/tensorflow/test_toml/modelbox.test.cpu.tensorflow.in
- src/drivers/devices/cuda/flowunit/mindspore_inference/test_toml/modelbox.test.mindspore.cuda.inference.in
- src/drivers/devices/cuda/flowunit/tensorflow/tensorflow_gpu_inference_flowunit.h
- src/drivers/devices/cuda/flowunit/tensorflow/test_toml/modelbox.test.cuda.tensorflow.in
- src/drivers/devices/cuda/flowunit/tensorflow/test_toml/modelbox.test.cuda.tensorflow.savemodel.in
- src/drivers/devices/cuda/flowunit/tensorrt/tensorrt_inference_flowunit.cc
- src/drivers/devices/cuda/flowunit/tensorrt/tensorrt_inference_flowunit.h
- src/drivers/devices/cuda/flowunit/tensorrt/test_toml/modelbox.test.plugin.tensorrt.in
- src/drivers/devices/cuda/flowunit/tensorrt/test_toml/modelbox.test.tensorrt.in
- src/drivers/devices/cuda/flowunit/torch/test_toml/modelbox.test.torch.in
- src/drivers/devices/cuda/flowunit/torch/torch_inference_flowunit.cc
- src/drivers/inference_engine/mindspore/mindspore_inference.cc
- src/drivers/inference_engine/mindspore/mindspore_inference.h
- src/drivers/inference_engine/mindspore/mindspore_inference_flowunit.cc
- src/drivers/inference_engine/tensorflow/tensorflow_inference_common.cc
- src/drivers/inference_engine/tensorflow/tensorflow_inference_common.h
- src/drivers/virtual/inference/virtualdriver_inference.cc
- src/drivers/virtual/inference/virtualdriver_inference.h
- src/libmodelbox/engine/flowunit.cc
- src/libmodelbox/include/modelbox/flowunit.h
- src/modelbox/serving/serving.cc
- src/modelbox/serving/serving.h
- src/modelbox/serving/test_file/model.toml.in
optimize inference toml config
> optimize inference toml config

- .github/workflows/publish-modelbox-images.yml
- docker/Dockerfile.ascend.develop.ubuntu
- docker/Dockerfile.ascend.runtime.ubuntu
- docker/Dockerfile.cuda.develop.ubuntu
- docker/Dockerfile.cuda.runtime.ubuntu
ubuntu 20.04镜像使用python3.8版本，mindspore升级到1.9.0版本
> image: ubuntu20.04 change to python3.8 and mindspore1.9.0

- src/drivers/devices/cuda/flowunit/tensorrt/tensorrt_inference_flowunit.cc
> trt5.x build failed

- .github/workflows/manual-build-with-rockchip-images.yml
- docker/Dockerfile.rknnrt.build.ubuntu
- docker/prepare_for_rockchip.sh
build rockchip 356x or 3588 image
> build rockchip 356x or 3588 image

- examples/bin/template
- examples/project/base/readme.txt
- examples/project/car_detection/setup.sh
- examples/project/emotion_detection/download_emotion_files.sh
- examples/project/emotion_detection/setup.sh
- examples/project/resize/test/flowunit/resize_flowuint_test.cc
template project can not run without modify
> [bug]template project can not run without modify

- src/drivers/devices/cpu/flowunit/output_broker/broker_plugin/webhook_output_broker/webhook_output_broker.cc
- src/drivers/devices/cpu/flowunit/output_broker/broker_plugin/webhook_output_broker/webhook_output_broker.h
> fix: multi channel webhook bug

- .github/workflows/publish-modelbox-images.yml
- docker/Dockerfile.ascend.develop.openeuler
- docker/Dockerfile.ascend.develop.ubuntu
- docker/Dockerfile.ascend.runtime.openeuler
- docker/Dockerfile.ascend.runtime.ubuntu
- docker/Dockerfile.cuda.runtime.ubuntu
- docker/prepare_for_dev.sh
- docker/prepare_for_run.sh
1. 迁移armd镜像构建到github云上环境
2. 更新github构建环境变量导入方式以及action版本
> update armd image build

- src/drivers/devices/ascend/flowunit/inference/atc_inference.cc
- src/drivers/devices/ascend/flowunit/inference/atc_inference.h
support dynamic batchsize for acl infer
> support dynamic batchsize for acl infer
